import prisma from 'config/prisma';
const hitosProfesionales = [
  {
    id: 1,
    user_id: 3,
    cvId: 'cklitcxil02035kfftqh0frok',
    empresa: 'CITIBANK',
    cargo: 'Cajero',
    funciones: '',
    paisId: 46,
    fechaInicio: '1996/03/01',
    fechaFin: '1996/12/06',
    tipoId: 1,
    funciones__1: 'Atención de Clientes en la Oficina Principal de Bucaramanga.',
    logros: 'Interacción con la banca empresarial.\nAprendizaje aplicado de la formación universitaria.',
  },
  {
    id: 2,
    user_id: 3,
    cvId: 'cklitcxil02035kfftqh0frok',
    empresa: 'Banco Central Hipotecario',
    cargo: 'Analista de Crédito Hipotecario',
    funciones:
      'El Banco Central Hipotecario, BCH, fue hasta su liquidación, el banco estatal mas importante en créditos hipotecarios.',
    paisId: 46,
    fechaInicio: '1997/01/07',
    fechaFin: '1997/12/19',
    tipoId: 2,
    funciones__1:
      'Análisis de Créditos individuales para compra de vivienda.\nAnálisis de Créditos para proyectos de construcción y subrogación individual.\nCoordinación de desembolsos con tesorería corporativa.',
    logros: 'Cumplimiento de metas operacionales y cronogramas.',
  },
  {
    id: 3,
    user_id: 3,
    cvId: 'cklitcxil02035kfftqh0frok',
    empresa: 'Compañía Central de Inversiones  S.A. - CISA',
    cargo: 'Director Inmobiliario Regional',
    funciones:
      'Central de Inversiones S.A. es la sociedad creada por el estado para la administración y venta de activos recibidos por las entidades bancarias estatales producto de la crisis financiera del año 1998.',
    paisId: 46,
    fechaInicio: '1998/09/01',
    fechaFin: '2000/02/01',
    tipoId: 2,
    funciones__1:
      'Administración y venta del inventario de Bienes Recibidos en Pago por la Regional Centro Oriente del Banco Central Hipotecario; con 29 oficinas a cargo.\nAnálisis de negocios de compraventa. \nRepresentante del BCH en la administración de los inmuebles. \nSelección y capacitación del equipo de ventas.',
    logros:
      'Cumplimiento de mentas de ventas de Activos Improductivos de la Regional. \nNegociación de cuotas de administración.',
  },
  {
    id: 4,
    user_id: 3,
    cvId: 'cklitcxil02035kfftqh0frok',
    empresa: 'AUDIOTEL S.A.',
    cargo: 'Supervisor de Administración y Finanzas',
    funciones:
      'Audiotel es la operadora tecnológica de servicios de Auditotexto y llamadas masivas del Grupo Clarín en Argentina.',
    paisId: 10,
    fechaInicio: '2000/02/02',
    fechaFin: '2002/01/31',
    tipoId: 2,
    funciones__1:
      'Estructuración Financiera, Administrativa y Contable del proyecto Hola!Cine hasta convertirlo en una Sociedad Anónima vinculada a Audiotel.  \nElaboración del modelo de costos para el sector de Call Center. \nMiembro del comité de diseño y puesta en marcha del proceso de planeación y control de presupuesto para todas las operaciones de la compañía. \nElaboración de informes y reportes para los accionistas.',
    logros:
      'Negociación de apertura de la línea de financiación para HolaCine S.A.\nConciliación histórica de ejecución de acuerdo de accionistas internacionales.',
  },
  {
    id: 5,
    user_id: 3,
    cvId: 'cklitcxil02035kfftqh0frok',
    empresa: 'Organización TERPEL S.A.',
    cargo: 'Gerente de Recursos Financieros - América Latina',
    funciones:
      'La Organización Terpel es la mas grande distribuidora de Combustibles en Colombia, con presencia adicional en Perú, y Panamá.',
    paisId: 46,
    fechaInicio: '2004/03/03',
    fechaFin: '2012/03/09',
    tipoId: 3,
    funciones__1:
      'Desarrollo de los procesos de Debida Diligencia y toma de control en el proceso de expansión internacional, mediante adquisiciones en Ecuador, Panamá, Chile, México y Perú. \nDirección de todas las operaciones de flujo de caja de la compañía: Crédito y Cartera, Recaudos, Inversiones de Tesorería.\nGestión de Apalancamiento y Riesgos y Seguros para las empresas del grupo en América Latina. Estructuración e implementación del proceso de centralización de operaciones de Riesgos, Tesorería y Cartera.',
    logros:
      'Consolidación de operaciones nacionales e internacionales de Cartera, Tesorería y Riesgos.\nDefinición de Políticas de Cartera para las todas las operaciones.\nImplementación exitosa de SAP en Colombia, Panamá y Ecuador.',
  },
  {
    id: 6,
    user_id: 3,
    cvId: 'cklitcxil02035kfftqh0frok',
    empresa: 'RS Corp. - Holding Grupo Sinergy.',
    cargo: 'Corporate CFO.',
    funciones:
      'RS Corp. reune el equipo corporativo y el Centro de Servicios Compartidos del Grupo Sinergy, propiedad de Germán Efromovich. (No incluye Avianca).',
    paisId: 46,
    fechaInicio: '2012/03/12',
    fechaFin: '2014/02/28',
    tipoId: 3,
    funciones__1:
      'Diseño de políticas Financieras, Contables, Tributarias, Cambiarias, de Tesorería, Endeudamiento e Inversiones, y en general todos los procesos financieros de la corporación y de las empresas que la conforman. Integración de las relaciones de las empresas con las entidades financieras locales e internacionales, para capturar sinergias y beneficios de la negociación de tipo corporativo. Seguimiento a la evolución de los portafolios de activos financieros por valor de USD 80 Millones, y operativos por valor de COP 450.000 Millones, tanto en la corporación como en las empresas operativas.  Liderar el proceso de implementación de NIIF para las empresas del grupo junto con el equipo del Centro de Servicios Compartidos.',
    logros:
      'Diseño, formación y consolidación del modelo de operación corporativa.\nNegociación de operaciones de crédito para las diferentes operaciones.\nEstructuración de negocios de construcción y operación hotelera.',
  },
  {
    id: 7,
    user_id: 3,
    cvId: 'cklitcxil02035kfftqh0frok',
    empresa: 'ARCANGELES - Fundación para la Rehabilitación Integral.',
    cargo: 'Gerente General',
    funciones: 'Fundación empresarial dedicada a la inclusión de personas con discapacidad.  Entidad sin ánimo de lucro.',
    paisId: 46,
    fechaInicio: '2014/03/03',
    fechaFin: '2015/10/31',
    tipoId: 3,
    funciones__1:
      'Definición de la nueva estrategia de la organización; Planeación y Presupuesto para la reorganización de la entidad; Diseño y ejecución de la reestructuración general.',
    logros:
      'Aumento de 36% en los ingresos promedio mensuales y una reducción de 60% en los costos. \nDesarrollo del correcto funcionamiento de los órganos de gobierno corporativo, y cumplimiento estricto con las obligaciones de reportes financieros y de operación a la Junta Directiva y a cooperantes nacionales e internacionales. \nNegociación y ejecución de convenios de cooperación internacional por valor superior a  US$1M.\nLas acciones ejecutadas se tradujeron en la reversión de resultados negativos para asegurar la sostenibilidad financiera de la organización.',
  },
  {
    id: 10,
    user_id: 14,
    cvId: 'cklitfvtj0987tcffyefixjce',
    empresa: 'Agencia Nacional de Defensa Jurídica del Estado',
    cargo: 'Experto (asesor)',
    funciones: 'Nivel asesor',
    paisId: 46,
    fechaInicio: '2015/07/10',
    fechaFin: '2019/06/04',
    tipoId: 2,
    funciones__1:
      'Poner en marcha y consolidar la Comunidad Jurídica del Conocimiento. Esta fue la apuesta de gestión de conocimiento de las anteriores administraciones de la Agencia, en la que armamos una red de aprendizaje y conocimiento en defensa jurídica a la que pertenecían cerca de 4.000 abogados de las diferentes entidades públicas nacionales.\n\nDesde el 28 de junio de 2018, he trabajado en litigio nacional, liderando el área de práctica de infraestructura y gerenciando el proyecto Negociatón, que pretende terminar los procesos en los que las dos partes son entidades públicas nacionales.',
    logros:
      'Más de 100 eventos realizados en tres años, más de 7.000 asistencias a eventos, más de 2.500 perfiles activos en la red virtual, más de $4.000 millones ejecutados en contratos.',
  },
  {
    id: 11,
    user_id: 2,
    cvId: 'cklitcvlj00035kffr2ene484',
    empresa: 'Oracle',
    cargo: 'Netsuite Sales Rep',
    funciones: '',
    paisId: 139,
    fechaInicio: '2018/06/01',
    fechaFin: '',
    tipoId: 2,
    funciones__1: 'Ventas Nesuite',
    logros: 'Overachivement',
  },
  {
    id: 12,
    user_id: 12,
    cvId: 'cklitfvj10868tcffhxgqle91',
    empresa: 'Banco Falabella Colombia',
    cargo: 'Analista de Proyectos',
    funciones: '',
    paisId: 46,
    fechaInicio: '2016/02/01',
    fechaFin: '2017/02/08',
    tipoId: 3,
    funciones__1:
      '• Reestructuración de procedimientos operativos de alto impacto en la compañía.\n• Estructuración y ejecución de proyectos en pro de implementar herramientas tecnológicas en procedimientos claves de la compañía.',
    logros:
      '• Definición proveedor para incorporación de tecnología OCR a sistema de otorgamiento de producto\n• Identificación de comportamientos de clientes en oficina a partir de información de los turnos solicitados\n• Definición de procedimientos para mejorar niveles de servicio a los clientes corporativos\n• Promoción de mejoras al portal corporativo',
  },
  {
    id: 13,
    user_id: 12,
    cvId: 'cklitfvj10868tcffhxgqle91',
    empresa: 'Tenaris TuboCaribe',
    cargo: 'Analista de planificación Industrial',
    funciones: '',
    paisId: 46,
    fechaInicio: '2017/02/28',
    fechaFin: '2019/01/14',
    tipoId: 3,
    funciones__1:
      '• Analizar comportamiento de KPIs para proponer a primera línea de dirección oportunidades de mejora, con base en resultados de operación.\n• Hacer seguimiento a planes de acción de mejora y participar en proyectos de alto impacto enfocados a mejorar la operación de la planta.\n• Realizar estructuración y control de costos de planta de producción.\n• Recolectar información para realizar y presentar balance de gestión a la primera línea de dirección.',
    logros:
      '• Participación en proyecto de reducción de costos de producción, generando un ahorro aproximado de 4.5 MM USD\n• Creación de modelo de costos para la primera planta de Ranurado de toda la organización a nivel mundial\n• Creación y ejecución de grupos de mejora que aumentaron utilización de diferentes líneas de producción',
  },
  {
    id: 14,
    user_id: 3,
    cvId: 'cklitcxil02035kfftqh0frok',
    empresa: 'Experian Colombia',
    cargo: 'Gerente de Planeación Financiera (Latam)',
    funciones: 'Líder mundial en soluciones de información para procesos de crédito y cobranza y analítica avanzada.',
    paisId: 46,
    fechaInicio: '2017/11/23',
    fechaFin: '2019/09/17',
    tipoId: 3,
    funciones__1:
      'Proceso de Planeación y Reportes para todos los países de Latam (Excl. Brasil). \nCoordinar la  Planeación Estratégica (5 años); elaborar el  Presupuesto (1 año) y el  Forecast mensual  (1 año).   Responsable de todos los procesos de Reporte mensual y regular a nivel regional y a nivel global.\nControl de Ejecución.',
    logros:
      'Evolución del indicador de gestión del área de planeación financiera, pasando del 58% al 83%.  \nReducción de 3 a 1 día en el proceso de reportes de cierre mediante automatización.  \n90% de efectividad en indicador global de efectividad en proceso de reportes.',
  },
  {
    id: 15,
    user_id: 3,
    cvId: 'cklitcxil02035kfftqh0frok',
    empresa: 'Integral de Servicios Técnicos',
    cargo: 'Gerente Financiero y Administrativo',
    funciones:
      'Empresa especializada en provisión de servicios para la industria petrolera, transporte de carga extra-dimensionada, carga seca, carga líquida, consultoría especializada en perforación y operación. Empresa en proceso de liquidación judicial.',
    paisId: 46,
    fechaInicio: '2017/05/15',
    fechaFin: '2017/11/22',
    tipoId: 3,
    funciones__1:
      'Responsable de la ejecución de procesos financieros y administrativos durante la reorganización empresarial y entrega al liquidador judicial nombrado por la Superintendencia de Sociedades. Encargado de la negociación con entidades financieras y proveedores de bienes y servicios.  Estructuración de procesos de ventas de activos improductivos, gestión de Costos y Flujo de Caja, vigilancia de obligaciones legales asociadas al proceso de reorganización.',
    logros:
      'Renegociación de obligaciones financieras con la banca nacional.   \nCierre de Estados Financieros atrasados. \nEntrega estructurada a liquidación judicial solicitada por la Junta Directiva.',
  },
  {
    id: 16,
    user_id: 3,
    cvId: 'cklitcxil02035kfftqh0frok',
    empresa: 'BRIGARD & URRUTIA Abogados',
    cargo: 'Director de Gestión Humana',
    funciones:
      'Firma líder de servicios legales en Colombia, con más de 80 años de operación, formada por más de 150 abogados en múltiples áreas de práctica profesional.',
    paisId: 46,
    fechaInicio: '2015/10/01',
    fechaFin: '2016/08/31',
    tipoId: 2,
    funciones__1:
      'Responsable de la revisión e implementación del Manual de Buenas Prácticas en Gestión del Talento, modificación del Plan de Desarrollo incorporando variables cuantitativas en la compensación y gestión del talento; valoración de ajustes al modelo de compensación y reestructuración de la unidad de apoyo de la firma, definición de nuevos procesos y responsabilidades. Apoyo a la Gerencia General en la elaboración de modelos financieros para nuevos negocios de expansión y crecimiento orgánico o mediante adquisiciones en otros lugares del país y de América Latina.',
    logros:
      'Elaboración de nuevo modelo de calificación para Plan de Desarrollo de abogados.  \nImplementación de nuevo modelo de beneficios.\nReorganización del área.',
  },
  {
    id: 17,
    user_id: 22,
    cvId: 'cklitfvdw0798tcffgo84dbce',
    empresa: 'Gente DeMente SAS',
    cargo: 'Asociado',
    funciones: '',
    paisId: 46,
    fechaInicio: '2018/01/01',
    fechaFin: '',
    tipoId: 1,
    funciones__1: 'Crear\nInventar\nOperar \nhacer todo lo que me digan ...\nhacer caso',
    logros: 'logré esto y aquello y también aquello y también lo uno y lo otro, en cambio también eso que me pidieron.',
  },
  {
    id: 18,
    user_id: 27,
    cvId: 'cklitft5s0089tcffbqlr2yzz',
    empresa: 'Almacenes Suritodo',
    cargo: 'Gerente de sucursal',
    funciones: '',
    paisId: 46,
    fechaInicio: '2006/10/03',
    fechaFin: '2007/08/30',
    tipoId: 2,
    funciones__1:
      ' Elaboración de presupuestos definiendo los objetivos de venta a alcanzar para cada departamento o línea de negocio y por cada asesor de manera individual.\n  Supervisión en la atención en piso y gestión de ventas.\n  Manejo de inventarios, selectivos de inventario.\n  Informes y manejo de indicadores de gestión.\n  Arqueos de caja.\n  Asistir a conferencias en representación de la empresa.\n  Supervisión del personal de ventas en los stands de la empresa en ferias y exposiciones. \n Apertura de convenios empresariales. \n Influencia en la contratación del personal comercial y capacitación, asegurando que el personal de ventas y demás personal cuenten con un buen conocimiento del producto, asegurar que el personal disponga de la documentación actualizada de ventas',
    logros:
      'En el tiempo que labore, se logro consolidar un equipo funcional de alto rendimiento en donde la comunicación y el trabajo equipo logro cumplir con las metas comerciales definidas.',
  },
  {
    id: 19,
    user_id: 27,
    cvId: 'cklitft5s0089tcffbqlr2yzz',
    empresa: 'Almacenes Ivan Botero Gomez',
    cargo: 'Gerente de sucursal',
    funciones: '',
    paisId: 46,
    fechaInicio: '2007/09/03',
    fechaFin: '2010/11/08',
    tipoId: 2,
    funciones__1:
      ' Elaboración de presupuestos definiendo los objetivos de venta a alcanzar por cada zona y por cada asesor de manera individual. \n Diseño y presentación de estrategias de ventas e informes para el análisis de la dirección comercial. \n Supervisión del trabajo de los agentes comerciales, esto se lleva a cabo a través de conversaciones telefónicas, visitas a zonas, correos electrónicos, reuniones de trabajo, este análisis se hace con distintas periodicidades.\n  Influencia en la contratación del personal comercial y capacitación, asegurando que el personal de ventas y demás personal cuenten con un buen conocimiento del producto\n  Estudio y aprobación de créditos\n  Manejo de cartera, recaudo de cartera de difícil cobro.\n  Manejo de inventarios, selectivos de inventario. \n Arqueos de caja. \n Apertura de puntos de venta.',
    logros:
      'Como uno de mis principales logros, puedo resaltar el haber podido integrar un equipo de ventas y cobranzas de casi 60 personas en donde se logro una excelente sincronía, empatia de un cargo al otro en donde los resultados alcanzados fueron el fruto de las metas inicialmente trazadas.',
  },
  {
    id: 20,
    user_id: 27,
    cvId: 'cklitft5s0089tcffbqlr2yzz',
    empresa: 'Fedco S.A.',
    cargo: 'Administrador de Tienda',
    funciones: '',
    paisId: 46,
    fechaInicio: '2011/04/11',
    fechaFin: '2014/01/31',
    tipoId: 2,
    funciones__1:
      ' Elaboración de presupuestos definiendo los objetivos de venta a alcanzar por la tienda, sus distintos departamentos y cada asesor de manera individual. \n Supervisión de los agentes comerciales en piso, inspección de la correcta ejecución de la exhibición de cada línea, mediante reuniones, acompañamiento y ejemplos en piso.\n  Asegurar que los productos siempre estén exhibidos de la mejor manera asegurando la correcta planimetría y que el producto tenga la correcta visibilidad de acuerdo a nivel de rotación en punto.\n  Diseño y presentación de estrategias de ventas e informes para el análisis de la dirección comercial.  Manejo y arqueos de caja.',
    logros: 'Incremento en ventas del 5% durante el último año y reducción en pérdidas de mercancía en un 2%',
  },
  {
    id: 21,
    user_id: 27,
    cvId: 'cklitft5s0089tcffbqlr2yzz',
    empresa: 'Comercializadora Inducascos',
    cargo: 'Jefe de zona',
    funciones: '',
    paisId: 46,
    fechaInicio: '2014/09/01',
    fechaFin: '',
    tipoId: 2,
    funciones__1:
      'Intervención en las decisiones de la compañía relacionadas con la comercialización de los productos.\n  Diseño y presentación de estrategias de ventas e informes para el análisis de la dirección comercial.  Elaboración de presupuestos definiendo los objetivos de venta a alcanzar por cada zona y por cada asesor de manera individual, indicadores de gestión. \n Distribución del trabajo por región o tipo asignándolo al personal de ventas. \n Supervisión del trabajo de los agentes comerciales, esto se lleva a cabo a través de conversaciones telefónicas, visitas a zonas, correos electrónicos, reuniones de trabajo, este análisis se hace con distintas periodicidades. \n Influencia en la contratación del personal comercial y capacitación, asegurando que el personal de ventas y demás personal cuenten con un buen conocimiento del producto, asegurar que el personal disponga de la documentación actualizada de ventas. \n Resolución de situaciones, quejas y/o consultas que surjan relacionadas con mi área, así como tratar y mantener buenas relaciones con los clientes.',
    logros:
      'He logrado un crecimiento en ventas sostenido de un 33 a 35 % en donde la operación ha sido rentable en su totalidad para la compañía pasando de una participación total en ventas compañía de un 8% a un  15%.\nConsolidar un equipo de alto rendimiento donde cada uno cuenta con nivel de toma de decisión y ejecución  de sus funciones.\nSe ha logrado el desarrollo y crecimiento de clientes con un buen potencial de mercado no solo visto desde el punto de vista de incremento en compras sino en la profesionalización de la labor como tal.',
  },
  {
    id: 22,
    user_id: 25,
    cvId: 'cklitcybf03715kffnv3flflx',
    empresa: 'Banco Itaú',
    cargo: 'Gerente Nacional de Ventas de Cash Management',
    funciones:
      'Con Reporte al Gerente Nacional de Cash Management, con 4 Gerencias a nivel nacional enfocadas en el negocio de personas jurídicas en diferentes segmentos: Corporativo, Institucional, Empresarial y Pymes; con un equipo total de 41 funcionarios. Responsable de un volumen en cuenta corriente de COP$1.2 Billones y comisiones por valor de COP$25.000 Millones al año.',
    paisId: 46,
    fechaInicio: '2018/03/01',
    fechaFin: '2019/03/22',
    tipoId: 2,
    funciones__1:
      '1. Planificar, diseñar y ejecutar la estrategia de ventas para alcanzar el presupuesto asignado, definiendo objetivos y metas por zonales y gerentes.\n2. Dirigir, organizar y controlar el equipo de ventas a nivel nacional mediante un seguimiento sistemático de la gestión comercial.\n3. Garantizar a través de los Gerentes de Zona el cumplimiento del equipo de ventas en la entrega de ofertas, cierre, implementación y puesta en marcha de los negocios transaccionales originados por los Gerentes de segmento.\n4. Asegurar la interacción entre el equipo comercial y las áreas de apoyo, para garantizar la efectividad de los procesos.\n5. Desarrollar el potencial comercial del equipo a cargo.\n6. Velar por la rentabilidad suscrita con los clientes en los acuerdos de servicios y convenios de adquirencia.\n7. Acompañar y apoyar el análisis de casos de negocio para la presentación de ofertas que generen valor al manejo de los flujos transaccionales de los clientes.',
    logros:
      '1. Liderar y estructurar con las áreas de apoyo la optimización de funciones del equipo comercial, asegurando su enfoque en la gestión de ventas en más de un 90%.\n2. Definir la estrategia de normalización de tarifas de clientes a través de un plan de negociación de acuerdos comerciales y comunicaciones, logrando la recuperación de comisiones recurrentes por      COP$ 300 Millones al año apoximádamente.',
  },
  {
    id: 23,
    user_id: 25,
    cvId: 'cklitcybf03715kffnv3flflx',
    empresa: 'Banco Itaú',
    cargo: 'Banker Transaccional Banca Mayorista',
    funciones:
      'Con reporte al Responsable Nacional de la Banca Corporativa e Institucional, con 2 Gerentes de Cuenta y un Subgerente, para atender un grupo de clientes top, entre los que se encontraban grandes contratistas de infraestructura y empresas del sector de telecomunicaciones, servicios, energía y consumo masivo para la ciudad de Bogotá y Medellín. Responsable de un volumen de negocio de COP$ 3.5 Billones.',
    paisId: 46,
    fechaInicio: '2017/01/02',
    fechaFin: '2018/02/28',
    tipoId: 2,
    funciones__1:
      '1. Atender la transaccionalidad de la lista cerrada de clientes, en las cuales se agrupaban los grandes contratistas y concesionarios del país, así como los clientes top del sector de telecomunicaciones, servicios, energía y consumo masivo.\n2. Mapear el flujo operacional de los clientes del segmento, para presentar una oferta de valor junto con el equipo de especialistas por producto, que atienda las necesidades de las compañías.\n3. Estructurar e implementar productos a la medida de las necesidades de cada cliente para el manejo de su Tesorería.\n4. Rentabilizar la utilización de las líneas de crédito disponibles a través de figuras que  permitan al Banco estar recurrentemente en el flujo del cliente.\n5. Profundizar cada una de las relaciones de los clientes del segmento a cargo, a través de la venta cruzada del portafolio ofrecido por el Grupo Financiero.\n6. Buscar estrategias que permitan atomizar el volumen de negocio y la rentabilidad de las carteras de los Gerentes de Cuenta.',
    logros:
      '1. Estructurar plan de acción por cada uno de los clientes, logrando el posicionamiento del Banco en la transaccionalidad, apalancados en los procesos de financiación y potencializando el ingreso de la marca Itaú. \n2. Liderar la estrategia comercial del proyecto de integración tecnológica y operativa del Banco, logrando un proceso impecable de migración para más de 900 clientes transaccionales de la Banca Mayorista, en un tiempo récord de 8 meses.',
  },
  {
    id: 24,
    user_id: 25,
    cvId: 'cklitcybf03715kffnv3flflx',
    empresa: 'Banco Itaú',
    cargo: 'Gerente Regional Banca Corporativa Bogotá',
    funciones:
      'Con reporte al Responsable Nacional de la Banca Corporativa y Empresas, con 11 personas, 7 Gerentes de Cuenta, un Gerente de Zona y 3 Subgerentes, para gestionar la relación comercial de los clientes del segmento Corporativo de la ciudad de Bogotá. Responsable de un volumen de negocio de COP$ 5 Billones.',
    paisId: 46,
    fechaInicio: '2015/04/15',
    fechaFin: '2016/12/31',
    tipoId: 2,
    funciones__1:
      '1. Planear acciones para direccionar el equipo a la profundización y logro de los objetivos presupuestales.\n2. Presentar estrategias junto con el Gerente de Zona para logra los retos exigidos en cuenta corriente, comisiones vía mesa de dinero y atomización de captación de recursos. \n3. Prospectar y presentar casos de negocios de crédito estructurados de la regional a cargo.\n4. Hacer seguimiento a la gestión comercial del equipo liderado por el Gerente de Zona, encargado de la Transaccionalidad del Negocio.\n5. Hacer seguimiento a la cartera vencida y presentar junto con el equipo de recuperaciones los planteamientos de reestructuración y/o reperfilamiento requeridos para la continuidad del negocio.',
    logros:
      'Alinear e integrar el equipo comercial, luego del proceso de fusión Corpbanca-Helm,  logrando estabilizar el clima laboral y optimizando la motivación, compromiso y productividad.',
  },
  {
    id: 25,
    user_id: 25,
    cvId: 'cklitcybf03715kffnv3flflx',
    empresa: 'BBVA Colombia',
    cargo: 'Gerente de Zona Senior Regional Empresas Bogotá',
    funciones:
      'Con reporte al Gerente de la Regional Empresas Bogotá, con 7 personas, 6 Gerentes de Cuenta y 1 Gerente Transaccional, para mantener y profundizar clientes especializados por sector. Responsable de un volumen de negocio de COP$2.0 Billones.',
    paisId: 46,
    fechaInicio: '2013/07/01',
    fechaFin: '2015/03/31',
    tipoId: 2,
    funciones__1:
      '1. Plantear estrategias para el mantenimiento y profundización de los clientes.\n2. Direccionar al equipo para posicionar al Banco como entidad líder en la relación “empresa-sector financiero”. \n3. Promover en el equipo la gestión integral de los clientes para obtener relaciones balanceadas, que permitan crecer el Volumen de Negocio en forma rentable.\n4. Apalancar sinergias con los especialistas del Banco para diagnosticar y atender las necesidades de los clientes.\n5.Aprovechar la especialización de los Gerentes de Cuenta por sector para generar ofertas de valor focalizadas a cada segmento.',
    logros:
      'Implementar y desarrollar la estrategia de especialización de Gerente de Cuenta por sector empresarial, que permitió construir relaciones de largo plazo, posicionando al Banco y creciendo el volumen de negocio en forma rentable.',
  },
  {
    id: 26,
    user_id: 25,
    cvId: 'cklitcybf03715kffnv3flflx',
    empresa: 'BBVA Colombia',
    cargo: 'Gerente Banca de Empresas Avenida El Dorado',
    funciones:
      'Con reporte al Responsable de Banca de Empresas a nivel nacional, con 11 personas, 5 Ejecutivos de Cuenta y 6 Operativos, para gestionar la relación comercial de los clientes empresariales de la zona de influencia de la oficina. Responsable de un volumen de negocio de COP$390.000 Millones.',
    paisId: 46,
    fechaInicio: '2011/11/01',
    fechaFin: '2013/06/30',
    tipoId: 2,
    funciones__1:
      '1. Gestionar clientes actuales y potenciales de la zona de influencia.\n2. Formar, acompañar y  hacer seguimiento a los funcionarios del equipo de trabajo para el cumplimiento de los objetivos fijados.\n3. Estructurar ofertas para el manejo integral de la tesorería de los clientes de acuerdo con el tipo de negocio.\n4. Preparar programas financieros de los clientes para atención de sus necesidades de capital de trabajo y/o proyectos de inversión. \n5. Cumplir con los presupuestos definidos para cada uno de los rubros del balance y estado de resultados.',
    logros:
      'Formar y acompañar al equipo a cargo, desarrollándolos tanto en habilidades técnicas como profesionales, alcanzando el nivel de alto rendimiento requerido para el cumplimiento de los objetivos fijados.',
  },
  {
    id: 27,
    user_id: 25,
    cvId: 'cklitcybf03715kffnv3flflx',
    empresa: 'BBVA Colombia',
    cargo: 'Gerente de Zona Bogotá Norte',
    funciones:
      'Con reporte al Gerente Territorial Bogotá Norte, con 23 oficinas de la zona norte de Bogotá y 223 personas entre Gerentes de Oficina, Gestores Comerciales, Subgerentes y Equipo Operativo. Responsable de un volumen de negocio de COP$1.4 Billones.',
    paisId: 46,
    fechaInicio: '2009/02/01',
    fechaFin: '2011/10/31',
    tipoId: 2,
    funciones__1:
      '1. Definir estrategias comerciales para la consecución de los objetivos asignados.\n2. Hacer seguimiento a la dinámica de facturación de las sucursales que conforman la zona\n3. Realizar acompañamiento en el desarrollo del negocio.\n4. Administrar el recurso humano (Formación, promoción, traslado, entre otras).\n5. Generar negocios a través de sinergias con Filiales y Bancas especializadas.\n6. Cumplir con los presupuestos definidos para cada uno de los rubros del balance y estado de resultados.',
    logros:
      '1. Desarrollar en los Gerentes la habilidad de gestionar el negocio de una manera integral, lo que nos llevó como equipo a enfocar el resultado en función de la rentabilidad.\n2. Desarrollar en los equipos la capacidad de generar relaciones de largo plazo con clientes del segmento personal y empresarial, para originar nuevos referidos impactando positivamente la productividad.\n3. Estructurar planes de desarrollo y carrera del personal de la zona, lo que nos permitió cubrir casi en un 100% las vacantes con promociones internas e iniciar planes de sucesión.',
  },
  {
    id: 28,
    user_id: 25,
    cvId: 'cklitcybf03715kffnv3flflx',
    empresa: 'BBVA Colombia',
    cargo: 'Gerente Banca de Empresas Calle 100',
    funciones:
      'Con reporte al Responsable de Banca de Empresas a nivel nacional, con 6 personas, entre Ejecutivos de Cuenta y Equipo Operativo, para gestionar la relación comercial de los clientes empresariales de la zona de influencia de la oficina. Responsable de un volumen de negocio de COP$270.000 Millones.',
    paisId: 46,
    fechaInicio: '2006/06/01',
    fechaFin: '2009/01/31',
    tipoId: 2,
    funciones__1:
      '1. Gestionar clientes actuales y potenciales de la zona de influencia.\n2. Formar, acompañar y  hacer seguimiento a los funcionarios del equipo de trabajo para el cumplimiento de los objetivos fijados.\n3. Estructurar ofertas para el manejo integral de la tesorería de los clientes de acuerdo con el tipo de negocio.\n4. Preparar programas financieros de los clientes para atención de sus necesidades de capital de trabajo y/ ó proyectos de inversión. \n5. Cumplir con los presupuestos definidos para cada uno de los rubros del balance y estado de resultados.',
    logros:
      '1. Retomar el 1er puesto a nivel nacional y cerrar importantes negocios, luego de tener una tendencia negativa en la oficina, al potenciar el capital humano.  \n2. Formar y delegar actividades comerciales al personal operativo, creando un semillero de Gerentes de Cuenta al interior de la oficina y la Banca Empresarial.',
  },
  {
    id: 29,
    user_id: 25,
    cvId: 'cklitcybf03715kffnv3flflx',
    empresa: 'BBVA Colombia',
    cargo: 'Ejecutiva de Cuenta Banca Corporativa',
    funciones:
      'Con reporte al Gerente de Banca Corporativa de la Regional.  Entre septiembre de 1999 y junio de 2002 desempeñé el cargo en Cali y de julio de 2002 a mayo de 2006 en Bogotá. Responsable de un volumen de negocio superior a los COP$300.000 Millones, gestionando clientes de perfil corporativo con ventas anuales superiores a los USD50 Millones con presencia en Colombia o con relación global con BBVA.',
    paisId: 46,
    fechaInicio: '1999/09/01',
    fechaFin: '2006/05/31',
    tipoId: 1,
    funciones__1:
      '1. Vincular, mantener y profundizar los clientes del portafolio asignado.\n2. Estructurar ofertas para el manejo integral de la tesorería de los clientes de acuerdo con el tipo de negocio.\n3. Preparar programas financieros de los clientes para atención de sus necesidades de capital de trabajo y/o proyectos de inversión.\n4. Coordinar con el Gestor de BBVA encargado de manejar la relación global de los clientes, la atención de sus necesidades locales de acuerdo con políticas de casa matriz.   \n5. Cumplir con los presupuestos definidos para cada uno de los rubros del balance.',
    logros:
      '1. Desarrollar una base de clientes inactivos, logrando potenciar la relación y asegurando resultados rentables y sostenibles para el Banco.\n2. Afianzar la posición del Banco con varios de los clientes más importantes de Cali, a través de la consolidación de relaciones de largo plazo.',
  },
  {
    id: 30,
    user_id: 25,
    cvId: 'cklitcybf03715kffnv3flflx',
    empresa: 'BBVA Colombia',
    cargo: 'Profesional en entrenamiento',
    funciones: '',
    paisId: 46,
    fechaInicio: '1998/09/01',
    fechaFin: '1999/08/31',
    tipoId: 1,
    funciones__1: 'Cargo en Formación, con etapas de capacitación en diferentes áreas del Banco.',
    logros: 'Obtener una visión global del negocio bancario, para iniciar el plan de carrera en el sector financiero.',
  },
  {
    id: 31,
    user_id: 25,
    cvId: 'cklitcybf03715kffnv3flflx',
    empresa: 'Fundación AlasCinco',
    cargo: 'Voluntaria en temas comerciales',
    funciones:
      'AlasCinco es un modelo social basado en la corresponsabilidad que busca interrumpir la cadena de pobreza a partir de estrategias de sostenibilidad, donde se incluye a todos los grupos de interés para que se beneficien creando valor compartido.',
    paisId: 46,
    fechaInicio: '2019/06/03',
    fechaFin: '2020/01/16',
    tipoId: 1,
    funciones__1:
      'Apoyar el crecimiento del plan sostenible, a través de la comercialización de granola, la cual hace parte de los “Productos Espantadores del Hambre” de AlasCinco',
    logros:
      '1. Proponer el esquema de costeo por presentación de granola, para la negociación del precio de venta a clientes\n2. Acompañar al estudiante en práctica de la Universidad de la Sabana, en la implementación del CRM para clientes empresariales',
  },
  {
    id: 32,
    user_id: 26,
    cvId: 'cklitg8332011tcffdib312x4',
    empresa: 'Banco Pichincha S.A.',
    cargo: 'Analista de Soluciones Débito y Prepago',
    funciones: '',
    paisId: 46,
    fechaInicio: '2018/06/01',
    fechaFin: '',
    tipoId: 2,
    funciones__1:
      'Crear y renovar la oferta de valor de las soluciones débito y prepago, promoviendo el incremento en su adquisición y utilización. A su vez así encargado de gerenciar los proyectos planteados dentro de la Gerencia, de manera que estos sean llevados a cabo dentro de los tiempos planteados y en colaboración con las áreas involucradas. Garantizar la prestación de un servicio eficiente y acorde a las necesidades del mercado cambiante, mediante la planificación e implementación de estrategias, haciendo más eficientes los procesos en las diferentes etapas de vida de los productos, en colaboración con la franquicia Visa, las redes de bajo valor en Colombia (CredibanCo y Redeban) y las áreas internas involucradas en los diferentes procesos.',
    logros:
      '1) Documentar y actualizar los documentos y procesos de los productos para lograr su debido funcionamiento con las áreas involucradas.\n2) Incrementar la facturación de Tarjeta Débito y Crédito mediante la implementación de campañas.\n3) Liderar la implementación de:\na) Código de seguridad CVV2 en Tarjeta Débito y Prepago para poder realizar compras en comercio electrónico.\nb) Tecnología Contactless en Tarjeta Débito, Crédito y Prepago.\nc) Esquemas de seguridad para la prevención de fraude en comercio electrónico con Tarjeta Débito, Crédito y Prepago.\nd) Nuevo producto débito para soluciones empresariales.',
  },
  {
    id: 33,
    user_id: 26,
    cvId: 'cklitg8332011tcffdib312x4',
    empresa: 'Banco Pichincha S.A.',
    cargo: 'Analista de Soluciones Débito',
    funciones: '',
    paisId: 46,
    fechaInicio: '2017/01/01',
    fechaFin: '2017/12/31',
    tipoId: 1,
    funciones__1:
      'Responsable del equipo de trabajo encargado de atender los requerimientos referentes a modificaciones y ajustes en colocaciones y captaciones, cumpliendo las metas propuestas por las Directivas y trabajando en conjunto con las Gerencias involucradas en el proceso, garantizando así el mejoramiento de los indicadores de cartera y atención de requerimientos. Elaborar los informes de rendimiento y control de indicadores.',
    logros:
      '1) Mejorar los indicadores de tiempo de atención de requerimientos en un 80%.\n2) Diseñar tableros de control que permitieron realizar un seguimiento detallado de las actividades ejecutadas por el equipo.\n3) Rediseñar los procesos de ejecución para lograr una mayor eficiencia en la atención de los requerimientos.',
  },
  {
    id: 34,
    user_id: 26,
    cvId: 'cklitg8332011tcffdib312x4',
    empresa: 'Banco Pichincha S.A.',
    cargo: 'Asistente operativo',
    funciones: '',
    paisId: 46,
    fechaInicio: '2013/09/01',
    fechaFin: '2016/12/31',
    tipoId: 1,
    funciones__1:
      'Modificar y corregir las colocaciones y captaciones evitando el incremento de la cartera vencida, así como mitigar la generación de sanciones para el banco por la generación de cobros errados. Generar reportes y estadísticas de los procesos ejecutados, en las diferentes líneas de producto, en aras de identificar las falencias que pudiesen existir y hacer más eficientes los procesos tanto internos como externos.',
    logros:
      '1) Mediante el rediseño de procesos se logró hacer más eficiente la atención de los requerimientos disminuyendo así los tiempos de atención.',
  },
  {
    id: 35,
    user_id: 26,
    cvId: 'cklitg8332011tcffdib312x4',
    empresa: 'Banco Pichincha S.A.',
    cargo: 'Asistente operativo',
    funciones: '',
    paisId: 46,
    fechaInicio: '2012/03/01',
    fechaFin: '2013/08/31',
    tipoId: 1,
    funciones__1:
      'Brindar atención al público buscando siempre dar solución a las diferentes inconformidades presentadas por los clientes, al igual que tramitar los procesos de traspaso y levantamiento de prenda sobre garantías que registran como respaldo de obligaciones financieras. A su vez gestionar debidamente los procesos de solicitud de crédito radicadas por la fuerza comercial.',
    logros: '1) Lograr una atención satisfactoria para los clientes de un 80%.',
  },
  {
    id: 36,
    user_id: 26,
    cvId: 'cklitg8332011tcffdib312x4',
    empresa: 'Interdinco S.A.',
    cargo: 'Asesor Call Center Servicio al Cliente',
    funciones: '',
    paisId: 46,
    fechaInicio: '2011/01/01',
    fechaFin: '2012/02/29',
    tipoId: 1,
    funciones__1:
      'Brindar atención telefónica a los clientes internos y externos del Banco Pichincha y a su vez suministrar asesoramiento sobre los diferentes servicios ofrecidos por la entidad.',
    logros: '1) Lograr una atención de las llamadas en un 100%.',
  },
  {
    id: 37,
    user_id: 31,
    cvId: 'cklitcvvo00185kffmeluft3i',
    empresa: 'Origen Sano',
    cargo: 'Fundador',
    funciones: '',
    paisId: 46,
    fechaInicio: '2012/04/01',
    fechaFin: '2018/08/13',
    tipoId: 3,
    funciones__1:
      'Definir el norte de la empresa. Coordinar a todos los departamentos de la compañía para conseguir nuestro objetivo de negocio y de impacto.',
    logros: 'Mejor emprendimiento social en Colombia por la Asociación Nacional de Industriales de Colombia (ANDI) 2017.',
  },
  {
    id: 38,
    user_id: 37,
    cvId: 'cklitfudf0412tcff5xjdwhhg',
    empresa: 'I.T.S.SERVICE',
    cargo: 'ASESOR ACADEMICO',
    funciones: '',
    paisId: 46,
    fechaInicio: '2003/01/25',
    fechaFin: '2007/02/25',
    tipoId: 1,
    funciones__1: 'ENSEÑANZA',
    logros: 'ENSEÑARLE INGLES A NIÑOS ,JOVENES, ADULTOS',
  },
  {
    id: 39,
    user_id: 47,
    cvId: 'cklitcx5801495kff6ciai38v',
    empresa: 'Centro educativo celestin freinet',
    cargo: 'Docente titular',
    funciones: '',
    paisId: 46,
    fechaInicio: '2004/02/13',
    fechaFin: '2019/11/13',
    tipoId: 2,
    funciones__1: 'Docente titular',
    logros: 'Grados de primaria y preescolar',
  },
  {
    id: 40,
    user_id: 53,
    cvId: 'cklitcwql00905kfffqzvclz4',
    empresa: 'Centro educativo Springfield school',
    cargo: 'Docente',
    funciones: '',
    paisId: 46,
    fechaInicio: '2018/01/15',
    fechaFin: '',
    tipoId: 1,
    funciones__1: 'Docente titular de un grado estipulado\nA cargo planeaciónes de clases y eventos educativos en la institución',
    logros:
      'Implementè mi conocimiento y con ellos logré llevar a cabo la independencia de cada niño. \nLos preparé para el grado primero.',
  },
  {
    id: 41,
    user_id: 48,
    cvId: 'cklitcxwq02715kffqbp5hl0x',
    empresa: 'Idectsa and Springfield',
    cargo: 'Docente',
    funciones: '',
    paisId: 46,
    fechaInicio: '2019/09/13',
    fechaFin: '',
    tipoId: 2,
    funciones__1:
      'Transmitir el conocimiento del inglés de una manera práctica y dinámica, logrando así un buen nivel en los estudiantes.',
    logros: 'Desarrollé competencias comunicativas y fluidez',
  },
  {
    id: 42,
    user_id: 51,
    cvId: 'cklitfu0n0279tcff50t19emv',
    empresa: 'Springfield',
    cargo: 'Psicóloga',
    funciones: '',
    paisId: 46,
    fechaInicio: '2019/01/21',
    fechaFin: '',
    tipoId: 2,
    funciones__1: 'Velar por el bienestar de los trabajadores y estudiantes',
    logros: 'Capacidad para resolver las distintas situaciones presentadas',
  },
  {
    id: 43,
    user_id: 49,
    cvId: 'cklitcz0605395kffjt7hnwmz',
    empresa: 'Centro educativo pepe grillo, liceo jorge tadeo lozano, springfield school',
    cargo: 'Docente',
    funciones: '',
    paisId: 46,
    fechaInicio: '2018/01/22',
    fechaFin: '',
    tipoId: 2,
    funciones__1: 'Docente titular',
    logros: 'Cumplir con lo planeado',
  },
  {
    id: 44,
    user_id: 52,
    cvId: 'cklitcw5k00425kff1fnl94go',
    empresa: 'Institución educativa San José Springfield academias de las Américas',
    cargo: 'Maestra titular y auxiliar docente',
    funciones: 'Se utilizó sonidos y palabras con imágenes de acuerdo a las consonantes a trabajar.',
    paisId: 46,
    fechaInicio: '2020/02/11',
    fechaFin: '',
    tipoId: 3,
    funciones__1: 'Enseñar ciertos temas. Obtener buenos resultados académicos',
    logros: 'Lectura y escritura',
  },
  {
    id: 45,
    user_id: 50,
    cvId: 'cklitczdn06865kffto5605um',
    empresa: 'Springfield school',
    cargo: 'Maestra',
    funciones: '',
    paisId: 46,
    fechaInicio: '2014/02/03',
    fechaFin: '',
    tipoId: 2,
    funciones__1: 'Maestra titular',
    logros: 'Experiencia en el campo de la enseñanza, aprendizaje y liderazgo',
  },
  {
    id: 46,
    user_id: 46,
    cvId: 'cklitcwql01025kffvybwdh89',
    empresa: 'Centro educativo Springfield school',
    cargo: 'Docente',
    funciones: 'Trabajar  el inglés en las diferentes áreas',
    paisId: 46,
    fechaInicio: '2019/03/01',
    fechaFin: '',
    tipoId: 2,
    funciones__1:
      'planeación del curso a cargo.\nSer el responsable del curso a cargo\nEjecutar actividades creativas, lúdicas y de aprendizaje en las diferentes áreas',
    logros: 'Manejar el idioma inglés, transversalmente',
  },
  {
    id: 47,
    user_id: 54,
    cvId: 'cklitcxwq02735kffwh8lxfwv',
    empresa: 'Springfield',
    cargo: 'Profesora',
    funciones: '',
    paisId: 46,
    fechaInicio: '2019/04/02',
    fechaFin: '',
    tipoId: 3,
    funciones__1: 'Orientar a los estudiantes y brindarle mis conocimientos',
    logros: 'Principalmente me gusta enseñar y que cada estudiante aprenda satifactoramente',
  },
  {
    id: 48,
    user_id: 45,
    cvId: 'cklitfsbe0020tcffssfj972p',
    empresa: 'Centro Educativo Springfield School',
    cargo: 'Docente preescolar',
    funciones: '',
    paisId: 46,
    fechaInicio: '2016/04/21',
    fechaFin: '',
    tipoId: 2,
    funciones__1:
      'Docente titular grado Párvulo año 2016\nDocente titular grado Pre jardín año 2017\nDocente titular multigrado (3 & 4) año 2019\nDocente titular multigrado (3, 4 & 5) año 2020\nRecibir y formar estudiantes desde la Educación Inicial hasta la básica primaria... Tomar sus saberes previos e impartir en ellos conocimientos nuevos, además de crear autonomía para su relación en la sociedad.',
    logros:
      '*Pronunciación de vocabulario en inglés y español.\n*Solución de situaciones problemas con operaciones básicas.\n*Cuidados del cuerpo humano y relación con los demás.\n*Ortografía y gramática \nTemas transversales Educación sexual, sociedad y paz.\nEntre otros.',
  },
  {
    id: 49,
    user_id: 19,
    cvId: 'cklitfvb90777tcff23842heg',
    empresa: 'Bavaria',
    cargo: 'Especialista Control Interno',
    funciones: '',
    paisId: 46,
    fechaInicio: '2008/03/03',
    fechaFin: '2014/11/04',
    tipoId: 3,
    funciones__1:
      'Validar la correcta ejecución de controles financieros a procesos estratégicos, y de soporte definidos por SABMiller.\nConsolidar, analizar y reportar por medio de indicadores el funcionamiento de la herramienta Control Self assessment requerida por la metodología de Control Interno de SABMiller.\nRealizar seguimiento al presupuesto de ingresos, costos y gastos de la Gerencia de Control Interno y la Vicepresidencia de Distribución asegurando la correcta ejecución del mismo. \nConsolidar, analizar y reportar indicadores financieros y operacionales cumpliendo con el cronograma de cierre y entrega requerida por la vicepresidencia Financiera.\nAnalizar, crear e informar las políticas, procedimientos, instructivos para soportar la operación de distribución a nivel nacional.',
    logros: 'Creación de controles SoX para las empresas del grupo SABMiller (Tapas, Etiquetas, Maltería)',
  },
  {
    id: 50,
    user_id: 19,
    cvId: 'cklitfvb90777tcff23842heg',
    empresa: 'Quantum Promocionales',
    cargo: 'Consultora Comercial',
    funciones: '',
    paisId: 46,
    fechaInicio: '2014/06/09',
    fechaFin: '2015/07/10',
    tipoId: 2,
    funciones__1:
      'Diseñar, analizar y presentar servicios de marketing y publicidad a nivel de promocionales, eventos, diseño y producción de stands.\nCoordinar y asegurar la correcta ejecución de los servicios contratados.\nNegociar tarifas y servicios contratados con proveedores. \nRealizar seguimiento a los pagos pendientes por realizar por parte de los clientes.',
    logros: 'Cerrar negociaciones con los clientes asignados.',
  },
  {
    id: 51,
    user_id: 19,
    cvId: 'cklitfvb90777tcff23842heg',
    empresa: 'Aerorepública S.A',
    cargo: 'Ejecuiva de Ventas',
    funciones: '',
    paisId: 46,
    fechaInicio: '2015/07/13',
    fechaFin: '',
    tipoId: 2,
    funciones__1:
      'Realizar visitas periódicas a las agencias Top y clientes Corporativos con el fin de soportar el cumplimiento de las metas establecidas así como la organización de actividades de promoción de los diferentes productos de Copa Airlines  para promover las ventas.\nAnalizar la información disponible sobre ingresos, participación de mercado y ajustar las acciones de ventas (visitas, seminarios, eventos) con el fin de identificar las oportunidades y debilidades en los diferentes mercados.\nInformar y actualizar a las áreas correspondientes sobre las acciones y actividades de la competencia y propias para que se tomen las medidas respectivas. \nElaborar y administrar el presupuesto de costos fijos de la operación de la venta a bordo de Wingo.\nRealizar los cierres financieros y contables de la venta a bordo de acuerdo con los requerimientos establecidos.\nAdministrar los contratos vigentes con los proveedores de catering con el fin de maximizar ingresos adicionales de la compañía por concepto de ventas a bordo.\nDiseñar indicadores y controles que permitan realizar seguimiento a la operación de venta a bordo y la oportuna toma de decisiones.\nRealizar revisiones mensuales de producto con el área de mercadeo y el proveedor de acuerdo con los lineamientos establecidos en el contrato.\nParticipar en la definición del portafolio de productos y servicios de ventas a bordo.\nDefinir política de incentivos para los tripulantes y revisar su correcta ejecución.\nDiseñar y entrenar a la tripulación de Wingo en el modelo de servicio para la venta a bordo.\nPreparar información de la gestión de las ventas a bordo para la junta directiva.\nDefinir y gestionar la implementación del proyecto de dispositivos móviles en la venta a bordo de Wingo con el fin de mitigar los riesgos tributarios y good will de la marca.',
    logros:
      'Creación y puesta en marcha del modelo de servicio y venta a bordo de la marca Wingo.\nImplementación de sistema de facturación a bordo.\nLograr y superar la rentabilidad del negocio de la venta a bordo.\nDesempeño destacado en el cumplimiento de objetivos anuales.',
  },
  {
    id: 52,
    user_id: 61,
    cvId: 'cklitfvvn1007tcffqlbta8eh',
    empresa: 'CAFAM',
    cargo: 'Prácticante desarrollo corporativo',
    funciones: '',
    paisId: 46,
    fechaInicio: '2019/07/15',
    fechaFin: '2020/01/15',
    tipoId: 3,
    funciones__1:
      '-Manejo de indicadores estratégicos\n-Manejo y consolidación de razones financieras de la compañía\n-Investigación de mercados de los negocios de la compañía',
    logros: 'Encontrar nuevas oportunidades de negocios y mejoramiento de los mismos.',
  },
  {
    id: 53,
    user_id: 67,
    cvId: 'cklitg5eu1126tcffkpuk313q',
    empresa: 'Colcafe S.A.S',
    cargo: 'Auxiliar de Mantenimiento',
    funciones: '',
    paisId: 46,
    fechaInicio: '2019/02/04',
    fechaFin: '2019/08/03',
    tipoId: 2,
    funciones__1:
      'Colaborar en las diferentes gestiones administrativas del área de mantenimiento, junto con el levantamiento de la taxonomía de la planta y el manejo de SAP.',
    logros:
      'Manejo y supervisor de personal, crecimiento en mi expresión personal, emprendimiento de proyectos dentro de la compañía.',
  },
];
const DBMigrate = async (req, res) => {
  if (req.method === 'GET') {
    const errores = [];
    await hitosProfesionales.forEach(async (hito) => {
      try {
        await prisma.hitoProfesional.create({
          data: {
            fechaInicio: new Date(hito.fechaInicio),
            cv: {
              connect: {
                id: hito.cvId,
              },
            },
            cargo: hito.cargo,
            empresa: hito.empresa,
            funciones: hito.funciones,
            logros: hito.logros,
            descripcion: hito.logros,
            pais: {
              connect: {
                id: hito.paisId,
              },
            },
            tipo: {
              connect: {
                id: hito.tipoId,
              },
            },
            fechaFin: hito.fechaFin === '' ? null : new Date(hito.fechaFin),
          },
        });
      } catch {
        errores.push(hito);
      }
    });
    return res.status(200).json({ errores });
  }
};

export default DBMigrate;
