import prisma from 'config/prisma';
const users = [
  {
    name: 'Julian Mesa',
    email: 'julianmesap@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1989/03/26',
    typeDocument: 'CC',
    document: 1010182021,
  },
  {
    name: 'HUGO PRADA',
    email: 'hfprada@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1978/01/13',
    typeDocument: 'CC',
    document: 13511949,
  },
  {
    name: 'Criadero El Quincho',
    email: 'criaderoelquincho@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '2000/01/18',
    typeDocument: 'CC',
    document: 13511949,
  },
  {
    name: 'HUGO PRADA',
    email: 'hugo@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1978/01/13',
    typeDocument: 'CC',
    document: 13511949,
  },
  {
    name: 'HUGO HOTMAIL',
    email: 'hugoprada@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1980/01/13',
    typeDocument: 'CC',
    document: 13511949,
  },
  {
    name: 'Cristina Lozano',
    email: 'crisana82@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1982/06/10',
    typeDocument: 'CC',
    document: 52844281,
  },
  {
    name: 'Cristina Lozano',
    email: 'crisana82@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1982/06/10',
    typeDocument: 'CC',
    document: 52844281,
  },
  {
    name: 'Maria Catalina Fajardo Trujillo',
    email: 'catalinafajardo@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1986/05/05',
    typeDocument: 'CC',
    document: 1019006517,
  },
  {
    name: 'LUZ AIDA VILLATE CACERES',
    email: 'luzavillatecaceres@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1984/01/13',
    typeDocument: 'CC',
    document: 52735805,
  },
  {
    name: 'Andres Diaz',
    email: 'af.diaz1404@test-gdm.edu.co',
    gender: 'Masculino',
    fechaNacimiento: '1993/12/28',
    typeDocument: 'CC',
    document: 1098747753,
  },
  {
    name: 'Sebastián Serna Arias',
    email: 'Sebastian.serna.arias@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1991/08/10',
    typeDocument: 'CC',
    document: 1020764121,
  },
  {
    name: 'Camilo Isaza Herrera',
    email: 'isazahcamilo@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1979/02/11',
    typeDocument: 'CC',
    document: 79948065,
  },
  {
    name: 'Monica Isaacs',
    email: 'MONICAISAACS75@test-gdm.COM',
    gender: 'Femenino',
    fechaNacimiento: '1975/08/21',
    typeDocument: 'CC',
    document: 66948878,
  },
  {
    name: 'Diana Mrcela Tiria Vasquez',
    email: 'diana.tiria@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1980/07/23',
    typeDocument: 'CC',
    document: 52698268,
  },
  {
    name: 'Tedi Quintero',
    email: 'tquinterosanchez@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1989/05/25',
    typeDocument: 'CC',
    document: 1020742492,
  },
  {
    name: 'Alejandra Londoño',
    email: 'alejandra.londono.alvarez@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1983/03/11',
    typeDocument: 'CC',
    document: 32241841,
  },
  {
    name: 'Vianny Carolina Cano Delgado',
    email: 'caritocanod@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1982/06/17',
    typeDocument: 'CC',
    document: 63530472,
  },
  {
    name: 'Laura Isabel Lizarazo Roa',
    email: 'laurallizarazo21@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1988/09/13',
    typeDocument: 'CC',
    document: 1098663009,
  },
  {
    name: 'Laura Lizarazo',
    email: 'lauralizarazo21@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1988/09/13',
    typeDocument: 'CC',
    document: 1098663009,
  },
  {
    name: 'HUGO PRUEBA',
    email: 'hugocvgdm@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1970/01/13',
    typeDocument: 'CC',
    document: 13511959,
  },
  {
    name: 'Diana Buitrago Izquierdo',
    email: 'diana.buitrago.izquierdo@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1988/01/04',
    typeDocument: 'CC',
    document: 1015404149,
  },
  {
    name: 'HUGO PRADA',
    email: 'HUGO.PRADA@test-gdm.COM',
    gender: 'Femenino',
    fechaNacimiento: '1978/01/13',
    typeDocument: 'CC',
    document: 13511949,
  },
  {
    name: 'Marta Arboleda',
    email: 'martaarboledatrujillo@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1975/11/12',
    typeDocument: 'CC',
    document: 66954188,
  },
  {
    name: 'Germán Gómez',
    email: 'gergilede@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1992/06/11',
    typeDocument: 'CC',
    document: 1016046070,
  },
  {
    name: 'Carlos Ignacio Gutiérrez  Méndez',
    email: 'cgm091272@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1972/12/09',
    typeDocument: 'CC',
    document: 11320522,
  },
  {
    name: 'PAOLA ANDREA HIGUERA HURTADO',
    email: 'paohigue@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1982/08/11',
    typeDocument: 'CC',
    document: 52905776,
  },
  {
    name: 'Otro Hugo Prada',
    email: 'otrohugoprada@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1978/01/13',
    typeDocument: 'CC',
    document: 13511949,
  },
  {
    name: 'Sandra Díaz',
    email: 'Sandritadiaz@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '2019/03/15',
    typeDocument: 'CC',
    document: 52225606,
  },
  {
    name: 'Daniel Esteban Rocha Durán',
    email: 'daniel@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1991/10/03',
    typeDocument: 'CC',
    document: 1015426598,
  },
  {
    name: 'Adriana Gallo',
    email: 'adriana.marcela.gc@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '2019/08/14',
    typeDocument: 'CC',
    document: 63552380,
  },
  {
    name: 'Yohanna Ramírez',
    email: 'Ycrc2914@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '2020/02/15',
    typeDocument: 'CC',
    document: 52152442,
  },
  {
    name: 'Ana Patricia Mendoza López',
    email: 'anamendoza74@test-gdm.es',
    gender: 'Femenino',
    fechaNacimiento: '1974/01/30',
    typeDocument: 'CC',
    document: 52146484,
  },
  {
    name: 'Yudy Matallana',
    email: 'Yudymatallana@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1976/09/13',
    typeDocument: 'CC',
    document: 46677068,
  },
  {
    name: 'John Jairo Zuluaga Castrillón',
    email: 'jjzuluaga2000@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1983/08/16',
    typeDocument: 'CC',
    document: 80762435,
  },
  {
    name: 'FABIO MANTILLA',
    email: 'fabioalejandro32@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1982/01/13',
    typeDocument: 'CC',
    document: 3837033,
  },
  {
    name: 'JUAN PABLO LUQUERNA RECALDE',
    email: 'luquerna@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1983/09/03',
    typeDocument: 'CC',
    document: 80100055,
  },
  {
    name: 'Luis Gabriel Diaz',
    email: 'luisgdiaz@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1983/09/18',
    typeDocument: 'CC',
    document: 91522139,
  },
  {
    name: 'Katy Paola Pérez Salas',
    email: 'katty.perez2010@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '2020/09/13',
    typeDocument: 'CC',
    document: 1103110332,
  },
  {
    name: 'Oscar Eduardo Mantilla Bueno',
    email: 'oscar.mantillabueno@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1980/05/09',
    typeDocument: 'CC',
    document: 13741982,
  },
  {
    name: 'Deisy Walteros',
    email: 'deisywalteros@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1970/08/03',
    typeDocument: 'CC',
    document: 51999541,
  },
  {
    name: 'Jennifer Katherine Obredor Valenzuela',
    email: 'jenniferobredor@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1990/02/26',
    typeDocument: 'CC',
    document: 1013610534,
  },
  {
    name: 'Camilo Vélez',
    email: 'camilo.velez1829@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1982/01/19',
    typeDocument: 'CC',
    document: 94479326,
  },
  {
    name: 'Paula Andrea Romero Montes',
    email: 'proromero0397@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1997/04/21',
    typeDocument: 'CC',
    document: 1102877772,
  },
  {
    name: 'María Carolina Rivera Martínez',
    email: 'Maria.rivera@test-gdm.edu.co',
    gender: 'Femenino',
    fechaNacimiento: '1996/06/27',
    typeDocument: 'CC',
    document: 1102873269,
  },
  {
    name: 'Yennis helena Anaya Sierra',
    email: 'yennisanaya4@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1983/10/17',
    typeDocument: 'CC',
    document: 23182885,
  },
  {
    name: 'Julia Teresa Pacheco Ricardo',
    email: 'juliatere8@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1998/11/18',
    typeDocument: 'CC',
    document: 1102884867,
  },
  {
    name: 'Wadys patricia Gonzalez Toscano',
    email: 'jukase01@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1990/01/20',
    typeDocument: 'CC',
    document: 1102831110,
  },
  {
    name: 'Sindy paola Montes benitez',
    email: 'sindy.montesb@test-gdm.edu.co',
    gender: 'Femenino',
    fechaNacimiento: '1989/11/20',
    typeDocument: 'CC',
    document: 1101814121,
  },
  {
    name: 'Daniela Vergara ramos',
    email: 'danielavergararamos9@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1999/06/23',
    typeDocument: 'CC',
    document: 1102887859,
  },
  {
    name: 'Sandy María Guerra Vega',
    email: 'sandyguerravega31@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1994/12/31',
    typeDocument: 'CC',
    document: 1002184769,
  },
  {
    name: 'Ena Carolina Pérez Sierra',
    email: 'ecarolinaperez94@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1994/05/02',
    typeDocument: 'CC',
    document: 1102860973,
  },
  {
    name: 'Danila Ester Polo Romero',
    email: 'Mt2095@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1996/12/18',
    typeDocument: 'CC',
    document: 1005438156,
  },
  {
    name: 'Edgar GALVIS CARVAJAL',
    email: 'egalvisc@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1977/05/29',
    typeDocument: 'CC',
    document: 79961680,
  },
  {
    name: 'Erick david Torres rendon',
    email: 'erickdavid1995@test-gdm.es',
    gender: 'Masculino',
    fechaNacimiento: '1995/01/10',
    typeDocument: 'CC',
    document: 1012417753,
  },
  {
    name: 'Mila Pesa Mazzola',
    email: 'milapesa@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '2002/10/25',
    typeDocument: 'CC',
    document: 44553004,
  },
  {
    name: 'Andrea Jiménez',
    email: 'andrejime88@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1988/09/07',
    typeDocument: 'CC',
    document: 1020735048,
  },
  {
    name: 'Lorena Espinal',
    email: 'Llespinal@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1981/11/03',
    typeDocument: 'CC',
    document: 41951124,
  },
  {
    name: 'David Flórez',
    email: 'davidasociados@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1984/11/05',
    typeDocument: 'CC',
    document: 80828734,
  },
  {
    name: 'Andrés Felipe Góngora Ortiz',
    email: 'andres.gongor@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1997/05/07',
    typeDocument: 'CC',
    document: 1019129916,
  },
  {
    name: 'Juan Carlos Meza Lara',
    email: 'juan.meza.lara@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1977/10/30',
    typeDocument: 'CC',
    document: 79964420,
  },
  {
    name: 'Carolina Arango Gil',
    email: 'arangocaro7@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1983/12/07',
    typeDocument: 'CC',
    document: 52966689,
  },
  {
    name: 'Beatriz Elena Charris Mercado',
    email: 'b.charris16@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1994/05/16',
    typeDocument: 'CC',
    document: 1020793299,
  },
  {
    name: 'Merilay Holguin',
    email: 'merilay.holguin@test-gdm.co',
    gender: 'Femenino',
    fechaNacimiento: '1998/11/14',
    typeDocument: 'CC',
    document: 1083040825,
  },
  {
    name: 'Felipe Esteban Espitia Murcia',
    email: 'fespitiamurcia@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1993/04/27',
    typeDocument: 'CC',
    document: 1018458863,
  },
  {
    name: 'Stevenson Orjuela Baracaldo',
    email: 'stevenson.baracaldo@test-gdm.com',
    gender: 'Masculino',
    fechaNacimiento: '1995/04/18',
    typeDocument: 'CC',
    document: 1016075483,
  },
  {
    name: 'Guadalupe María Prieto Quintana',
    email: 'gmpq@test-gdm.com',
    gender: 'Femenino',
    fechaNacimiento: '1973/12/04',
    typeDocument: 'CC',
    document: 52404809,
  },
];

const DBMigrate = async (req, res) => {
  if (req.method === 'GET') {
    const errores = [];
    await users.forEach(async (user) => {
      try {
        await prisma.user.create({
          data: {
            email: user.email,
            name: user.name,
            Perfil: {
              create: {
                document: user.document.toString(),
                typeDocument: user.typeDocument,
                fechaNacimiento: new Date(user.fechaNacimiento),
                gender: user.gender,
                image: '',
              },
            },
            cv: {
              create: {},
            },
            roles: {
              connect: {
                id: 'ckkrbqn4y0011ngff2r1qhiw8',
              },
            },
            empresa: {
              connect: {
                id: 'ckli32pq202103gffiun09uhq',
              },
            },
          },
        });
      } catch {
        errores.push(user);
      }
    });
    return res.status(200).json({ errores });
  }
};

export default DBMigrate;
